### ISSUE TITLE
Documentation Request - readme

### ISSUE THREAD

**Issue by JulioPDX** [chuckablack/quokka#11]
Is it possible to add a readme for getting started? Thank you Chuck and keep up the great work!

**Comment by chuckablack** [comment]
Have you checked out the wiki for this repo? In it I have numerous pages detailing how quokka works, with lots of diagrams and such. The link to the wiki is right at the top of the main page for this ('quokka') repository.

**Comment by JulioPDX** [comment]
Ah yes, my mistake. Thank you Chuck, going to start playing with quokka very soon :)

**Comment by chuckablack** [comment]
Note that if you are doing 52-weeks-of-python, the end result will be that you will have built what I call 'quokka-prime', which does the same stuff as quokka, but has some implementation differences. I'm also doing a video series called 'quokka-prime-from-scratch', where I go through step-by-step building quokka-prime (assuming the viewer has Python knowledge). You might want to check those out as well.
